.TH projectM-PipeWire 1 "January 18, 2026"
.SH NAME
projectM-pipewire \- ProjectM module for PipeWire
.SH DESCRIPTION
This manual page documents the
.B projectM-pipewire
command.
.PP
.B projectM-pipewire
provides direct visualisation of PipeWire audio streams using
the projectM audio visualisation library.
.PP
.B projectM-pipewire
can be run from the
.B Applications
menu after it was installed.
.SH AUTHOR
projectM-PipeWire was adapted from projectM-PulseAudio for modern PipeWire audio systems.
.PP
Original PulseAudio version by Carmelo Piccione <Carmelo.Piccione+projectM@gmail.com>.
